version: "3.9"
services:
  perspectra-api:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: perspectra-api-debug
    env_file:
      - .env.dev
    ports:
      - "5001:5000"  # API port
      - "5678:5678"  # Debug port
    volumes:
      - ./:/app  # Mount the current directory to /app in the container